# Available analyzers: standard, english, simple, whitespace, stop, custom
# Default: "standard"
analyzers=standard,english,simple,whitespace,stop,custom


# Available similarities: bm25, classic, boolean
# Default: "bm25"
similarities=bm25,classic,boolean

# Directory path where the Lucene index will be stored.
# If not specified, defaults to "./index".
# Example: indexPath=./index
#indexPath=

# Path to the Cranfield dataset documents file.
# Default: "./cran/cran.all.1400"
# Example: cranDocumentsPath=./cran/cran.all.1400
#cranDocumentsPath=

# Path to the Cranfield queries file.
# Default: "./cran/cran.qry"
# Example: cranQueryPath=./cran/cran.qry
#cranQueryPath=

# Directory path where the retrieval results and evaluation outputs will be saved.
# Default: "./output"
# Example: outputDir=./output
#outputDir=

# Maximum number of top documents to retrieve per query.
# Default: 50
# Example: topKDocuments=50
#topKDocuments=

# Path to the TREC evaluation tool directory.
# Default: "./trec_eval-9.0.7"
# Example: trecEvalPath=./trec_eval-9.0.7
#trecEvalPath=

# Path to the Cranfield relevance judgments file (qrels).
# Default: "./cran/cranqrel"
# Example: cranqrelFilePath=./cran/cranqrel
#cranqrelFilePath=

# Comma-separated list of metrics for evaluation using TREC eval.
# Default: "map,P.5,iprec_at_recall.00"
# Example : trecEvalMetrics=map,iprec_at_recall.00,P.20,P.10,P.50,P.100
trecEvalMetrics=P.5,map,iprec_at_recall.00,P.10
